---
abstract: 'Sync configuration files across machines'
author:
  - 'Peter Shangov <pshangov@yahoo.com>'
build_requires:
  App::Cmd::Tester: 0
  File::Find: 0
  File::Slurp: 0
  File::Spec: 0
  File::Temp: 0
  Test::Differences: 0
  Test::More: 0
  Try::Tiny: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Rcsync
requires:
  App::Cmd::Simple: 0
  Config::General: 0
  File::Copy: 0
  File::HomeDir: 0
  File::Path: 0
  Path::Class: 0
  Ref::Explicit: 0
  Template: 0
  base: 0
  strict: 0
  warnings: 0
version: 0.02
